<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <Version>1.9.0</Version>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Raccoon Ninja Tools</Title>
        <Description>A collection of helpers and utilities to help improve and speed up development.</Description>
        <Copyright>Copyrighted to the author (Breno RdV).</Copyright>
        <PackageProjectUrl>https://github.com/brenordv/nuget-raccoon-tools</PackageProjectUrl>
        <PackageLicenseFile>license.txt</PackageLicenseFile>
        <RepositoryUrl>https://github.com/brenordv/nuget-raccoon-tools</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>utils utility toolset chsarp-library guid5 uuid5 uuidv5 uuid guid functional c-sharp csharp dotnetcore discriminated-unions extensions datetime list string</PackageTags>
        <PackageReleaseNotes>## [1.9.0] - Apr, 2025
- Changed the methods `Process` and `ProcessAsync` to `Match` and `MatchAsync` to adhere to the functional programming
  paradigm. The `Process` and `ProcessAsync` methods are still available, but they are marked as 
  obsolete and will be removed in the future;
- Added `IsSuccess`, `IsFailure`, `Error`, and `Value` properties to the `Result&lt;T&gt;` class to make it easier to
  use in OOP applications, while keeping the performance benefits of not throwing exceptions all around;</PackageReleaseNotes>
        <Authors>Breno RdV</Authors>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <AssemblyVersion>1.9.0</AssemblyVersion>
        <FileVersion>1.9.0</FileVersion>
        <NeutralLanguage>en-US</NeutralLanguage>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="../../license.txt" Pack="true" PackagePath="\" />
        <None Include="../../readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
