name: '.NET Build and Test'

on:
  workflow_call:
    inputs:
      project-path:
        description: 'Path to the project or solution file'
        required: true
      dotnet-version:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
      build-configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
  
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project-path }}
        shell: bash
  
      - name: Build
        run: dotnet build ${{ inputs.project-path }} --configuration ${{ inputs.build-configuration }} --no-restore
        shell: bash
  
      - name: Test
        run: dotnet test ${{ inputs.project-path }} --configuration ${{ inputs.build-configuration }} --no-build --verbosity normal
        shell: bash
