name: '.NET Build and Test'

on:
  workflow_call:
    inputs:
      projectOrSolutionPath:
        description: 'Path to the project or solution file'
        required: true
        type: string
      dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
        type: string
      buildConfiguration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository. Without this, the action will not have access to the code.
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Where Am I? What is going on?
        run: |
          echo "$(pwd) | ${{ inputs.projectOrSolutionPath }}"
          ls -la

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.projectOrSolutionPath }}
        shell: bash

      # Build the project
      - name: Build
        run: dotnet build ${{ inputs.projectOrSolutionPath }} --configuration ${{ inputs.buildConfiguration }} --no-restore
        shell: bash

      # Run tests
      - name: Test
        run: dotnet test ${{ inputs.projectOrSolutionPath }} --configuration ${{ inputs.buildConfiguration }} --no-build --verbosity normal
        shell: bash
