name: '.NET Build and Test'

on:
  workflow_call:
    inputs:
      projectPath:
        description: 'Path to the project or solution file'
        required: true
      dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
      buildConfiguration:
        description: 'Build configuration'
        required: false
        default: 'Release'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}
  
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.projectPath }}
        shell: bash
  
      - name: Build
        run: dotnet build ${{ inputs.projectPath }} --configuration ${{ inputs.buildConfiguration }} --no-restore
        shell: bash
  
      - name: Test
        run: dotnet test ${{ inputs.projectPath }} --configuration ${{ inputs.buildConfiguration }} --no-build --verbosity normal
        shell: bash
