name: Publish NuGet to Github Packages

on:
  workflow_call:
    inputs:
      projectPath:
        description: 'Path to the project directory'
        required: true
        type: string
      projectFile:
        description: 'Name of the project file'
        required: true
        type: string
      dotnetVersion:
        description: 'Version of .NET to use'
        required: true
        type: string

    secrets:
      githubToken:
        description: 'GitHub token to use for the workflow'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Build the project
        run: dotnet build ${{ inputs.projectPath }}/${{ inputs.projectFile }} --configuration Release

      - name: Create the NuGet package
        run: dotnet pack ${{ inputs.projectPath }}/${{ inputs.projectFile }} --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ inputs.githubToken }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.githubToken }}