name: Publish

on:
  push:
    branches:
      - deploy-pipelines

jobs:
  test-code:
    uses: brenordv/github-workflows/.github/workflows/template-build-and-test-dotnet.yml@v1
    with:
      projectOrSolutionPath: './src/Raccoon.Ninja.Tools.sln'

#  sonarcloud-analysis:
#    uses: brenordv/github-workflows/.github/workflows/template-qa-sonarcloud.yml@v1
#    with:
#      projectKey: 'brenordv_nuget-raccoon-tools'
#      organization: 'raccoon-ninja'
#      verbose: true
#      sonarExclusions: 'src/Raccoon.Ninja.Tools.*.Tests/**/*'
#      coverageExclusions: 'src/Raccoon.Ninja.Tools.*.Tests/**/*'
#      projectOrSolution: './src/'
#
#    secrets:
#      githubToken: ${{ secrets.GITHUB_TOKEN }}
#      sonarToken: ${{ secrets.SONAR_TOKEN }}

  create-release:
    needs: [test-code]

    permissions:
      deployments: write
      contents: write

    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

    uses: brenordv/github-workflows/.github/workflows/template-create-release-and-artifacts.yml@v1
    with:
        projectPath: './src/Raccoon.Ninja.Tools'
        projectFile: 'Raccoon.Ninja.Tools.csproj'
        csprojTag: 'Version'
        releaseFilePrefix: 'Raccoon.Ninja.Tools'
        isNugetPackage: true

  publish-to-github-packages:
    #needs: [sonarcloud-analysis, create-release] # TODO: restore this after finished creating this job.
    needs: [create-release]

    permissions:
      deployments: write
      contents: write

    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

    uses: ./.github/workflows/publish-to-github-packages.yml
    with:
      projectPath: './src/Raccoon.Ninja.Tools'
      projectFile: 'Raccoon.Ninja.Tools.csproj'
      dotnetVersion: '8.0.x'
      githubToken: ${{ secrets.GITHUB_TOKEN }}
